// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertBase64ToStr(arg1) {
  return window['go']['backend']['App']['ConvertBase64ToStr'](arg1);
}

export function ConvertStrToBase64(arg1) {
  return window['go']['backend']['App']['ConvertStrToBase64'](arg1);
}

export function IpInfo() {
  return window['go']['backend']['App']['IpInfo']();
}

export function LocationInfo() {
  return window['go']['backend']['App']['LocationInfo']();
}

export function SystemInfo() {
  return window['go']['backend']['App']['SystemInfo']();
}
