// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertBase64ToStr(arg1:string):Promise<string>;

export function ConvertStrToBase64(arg1:string):Promise<string>;

export function IpInfo():Promise<string>;

export function LocationInfo():Promise<string>;

export function SystemInfo():Promise<string>;
